dependencies:
	@which elixir || { \
	  cd $(shell mktemp -d) ;\
	  wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb ;\
	  sudo dpkg -i erlang-solutions_1.0_all.deb ;\
	  cd - ;\
	  sudo apt-get update -y ;\
	  sudo apt-get install -y elixir ;\
	}

.PHONY: dependencies
