dependencies: homebrew
	which elixir || brew install elixir

homebrew:
	which brew || ruby -e "$$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

.PHONY: dependencies homebrew
